#ifndef COMPPREFS_H
#define COMPPREFS_H

#define FRONT_RIGHT_TURN_OFFSET -15.0
#define FRONT_LEFT_TURN_OFFSET -105.0
#define BACK_RIGHT_TURN_OFFSET 15.0
#define BACK_LEFT_TURN_OFFSET -80.0

#define TURN_ENCODER_TYPE CANTalon::AnalogEncoder
#define ABSOLUTE_CONV_FACTOR 1024.0 / 360.0

#endif
