#ifndef COMPPREFS_H
#define COMPPREFS_H

#define FRONT_RIGHT_TURN_OFFSET 0
#define FRONT_LEFT_TURN_OFFSET 0
#define BACK_RIGHT_TURN_OFFSET 0
#define BACK_LEFT_TURN_OFFSET 0

#define FRONT_RIGHT_TURN_PID 0,0,0
#define FRONT_RIGHT_DRIVE_PIDF 0,0,0,0
#define FRONT_LEFT_TURN_PID 0,0,0
#define FRONT_LEFT_DRIVE_PIDF 0,0,0,0
#define BACK_RIGHT_TURN_PID 0,0,0
#define BACK_RIGHT_DRIVE_PIDF 0,0,0,0
#define BACK_LEFT_TURN_PID 0,0,0
#define BACK_LEFT_DRIVE_PIDF 0,0,0,0

#define TURN_ENCODER_TYPE CANTalon::AnalogEncoder
#define ABSOLUTE_CONV_FACTOR (1024.0 / 360.0)

#endif
