#ifndef PRACTICEPREFS_H
#define PRACTICEPREFS_H



#define FRONT_RIGHT_TURN_OFFSET 0
#define FRONT_LEFT_TURN_OFFSET 0
#define BACK_RIGHT_TURN_OFFSET 0
#define BACK_LEFT_TURN_OFFSET 0

#define TURN_ENCODER_TYPE CANTalon::PulseWidth
#define ABSOLUTE_CONV_FACTOR 4096.0 / 360.0

#endif
